name: Cypress Accessibility Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run accessibility tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://secure.splitwise.com'
          record: true
          spec: cypress/e2e/accesibilidad.cy.js # Especifica el archivo de prueba
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
